name: build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download
        go get github.com/mattn/goveralls

    - name: Test
      run: |
        go test -covermode=atomic -coverprofile=cover.out ./...
        go test ./testing -mod=readonly -race -timeout 30s
        $(go env GOPATH)/bin/goveralls -coverprofile=cover.out -service=github-actions -repotoken ${{ secrets.COVERALLS_TOKEN }}

    - name: Benchmark
      run: go test -bench=. -benchtime=1000x -run=XXX ./testing

    - name: Build
      run: go build -v ./broker/build/main.go
