name: build
on: [push]
jobs:

  build:
    name: Build 14
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download
        cd cmd/broker ; go mod download ; cd -
        go get github.com/mattn/goveralls && go mod tidy

    - name: Test
      run: |
        go test -mod=readonly -race -timeout 30s -covermode=atomic -coverprofile=cover.out.tmp ./...
        cat cover.out.tmp | grep -v "grpc.pb.go" > cover.out
        $(go env GOPATH)/bin/goveralls -coverprofile=cover.out -service=github-actions -repotoken ${{ secrets.COVERALLS_TOKEN }}

    - name: Benchmark
      run: go test -bench=. -benchtime=1000x -run=XXX ./benchmarks

    - name: Build
      run: cd cmd/broker && CGO_ENABLED=0 go build -mod=readonly -ldflags '-s -w' main.go
